### ISSUE TITLE
create FAQ and WIKI

### ISSUE THREAD

**Issue by pelsasser** [MarketProject/MarketProtocol#10]

**Comment by cryptomental** [comment]
This is very much needed for anyone that would like to contribute.

**Comment by pelsasser** [comment]
the FAQ is greatly updated - feel free to ask anything here that you think should be added.

**Comment by cryptomental** [comment]
Thank you @pelsasser ,  I will have a look today.

**Comment by cryptomental** [comment]
It is a good start. I would like to see there a step by step tutorial for two simple MarketProtocol use cases that use oraclize.

**Comment by pelsasser** [comment]
@cryptomental - sounds good, I will add an use case example or two in there.

**Comment by pelsasser** [comment]
this is getting moved to docs.marketprotocol.io so am closing this here
