### ISSUE TITLE
consider changing requirements for users to pre-commit collateral for trading.

### ISSUE THREAD

**Issue by pelsasser** [MarketProject/MarketProtocol#12]
Open to discussion!

**Pros of pre committing collateral**
- Order book hosts can monitor only the MarketCollateralPool contract to ensure sufficient balance for resting orders
- less external calls during tradeOrder call

**Cons**
- order book hosts will have to monitor each address to ensure orders still have sufficient balance behind them
- users are surrendering control of their tokens

**Comment by perfectmak** [comment]
Quick question, how does preventing pre-commit of collateral lead to less external calls during tradeOrder?

**Comment by pelsasser** [comment]
If the collateral token has already been deposited to the collateral contract prior to a trade we are just doing some account moving the balance from 
` mapping(address => uint) public userAddressToAccountBalance; ` to the 
`collateralPoolBalance`

Otherwise, when the `traderOrder` call is made, we have to transfer the balance from the user's external address to the ` collateralPoolBalance `

**Comment by perfectmak** [comment]
Okay, but maybe I'm missing something. If the collateral token is not pre-commited, that means we would have to transfer it from the users external address to the collateral pool before performing the trade when `tradeOrder()` is called, right?

Doesn't that mean we are making more external calls? and therefore isn't a **pro** of preventing pre-commiting of collateral?

**Comment by pelsasser** [comment]
@perfectmak - edited and clarified my original comment - hopefully that helps

**Comment by perfectmak** [comment]
Yes @pelsasser, It is clear now.

I  believe pre-committing collateral to the CollateralPool will make it easier to ensure a trade if possible. 
Because without pre-committing, the balance monitoring system would still need to perform some sort of lock (or capture) on the balances of the addresses involved before fulfiling an order; so why not just pre-commit them from the beginning?
