### ISSUE TITLE
MarketContractOraclize test cases depend on previous tests

### ISSUE THREAD

**Issue by cryptomental** [MarketProject/MarketProtocol#16]
Test environment is not cleaned after test case. I suspect that a proper tear down (afterEach) is needed to selfdestruct contracts or they should be redeployed / recreated in beforeEach as deployed() just checks that the contracts were deployed.

Symptom: copy the first test case and give it another name, then run `truffle test test/MarketContractOraclize.js`. Only the first test case passes

Example:

```
root@cc1e758c63a9:/app# truffle test test/MarketContractOraclize.js
Using network 'development'.

  Contract: MarketContractOraclize
    ✓ duplicated test case (4235ms)
    1) Trade occurs, cancel occurs, balances transferred, positions updated
    > No events were emitted
    ✓ Trade is unwound, correct collateral amount returns to user balances (1325ms)
    ✓ should only allow remaining quantity to be filled for an overfilled trade. (924ms)
    ✓ should only allow remaining quantity to be cancelled for an over cancelled trade. (865ms)
    ✓ should fail for attempts to fill expired order (691ms)
    ✓ should fail for attempts to cancel expired order (317ms)
    ✓ should fail for attempts to trade zero quantity (319ms)
    ✓ should fail for attempts to create maker order and fill as taker from same account (446ms)
    ✓ should fail for attempts to order and fill with price changed (574ms)


  9 passing (10s)
  1 failing

  1) Contract: MarketContractOraclize Trade occurs, cancel occurs, balances transferred, positions updated:
     Error: VM Exception while processing transaction: invalid opcode
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:43303:16)
      at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:331156:36
      at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:314196:9
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70564:24)
      at endReadableNT (_stream_readable.js:1054:12)
```

I noticed this during #8 implementation.

**Comment by pelsasser** [comment]
thanks @cryptomental  - I will attempt to reproduce and figure out what is going on here.  I am just getting back from vacation, apologize for the delay.

**Comment by pelsasser** [comment]
@cryptomental when you say give it a new name, are you saying the file name or the contract function call as in 

`contract('MarketContractOraclize', function(accounts) {...}`

`contract('MarketContractOraclize2', function(accounts) {...}`

From the truffle docs 

> Before each contract() function is run, your contracts are redeployed to the running Ethereum client so the tests within it run with a clean contract state.

**Comment by pelsasser** [comment]
I am having trouble reproducing this, I copied the 
`contract('MarketContractOraclize', function(accounts) {...}`
call in the same file and ran the tests.  Output is below.

> 
> truffle(develop)> test test/MarketContractOraclize.js
> Using network 'develop'.
> 
> 
> 
>   Contract: MarketContractOraclize
>     ✓ Trade occurs, cancel occurs, balances transferred, positions updated (823ms)
>     ✓ Trade is unwound, correct collateral amount returns to user balances (493ms)
>     ✓ should only allow remaining quantity to be filled for an overfilled trade. (462ms)
>     ✓ should only allow remaining quantity to be cancelled for an over cancelled trade. (338ms)
>     ✓ should fail for attempts to fill expired order (226ms)
>     ✓ should fail for attempts to cancel expired order (92ms)
>     ✓ should fail for attempts to trade zero quantity (128ms)
>     ✓ should fail for attempts to create maker order and fill as taker from same account (204ms)
>     ✓ should fail for attempts to order and fill with price changed (201ms)
> 
>   Contract: MarketContractOraclize
>     ✓ Trade occurs, cancel occurs, balances transferred, positions updated (770ms)
>     ✓ Trade is unwound, correct collateral amount returns to user balances (502ms)
>     ✓ should only allow remaining quantity to be filled for an overfilled trade. (492ms)
>     ✓ should only allow remaining quantity to be cancelled for an over cancelled trade. (367ms)
>     ✓ should fail for attempts to fill expired order (214ms)
>     ✓ should fail for attempts to cancel expired order (89ms)
>     ✓ should fail for attempts to trade zero quantity (134ms)
>     ✓ should fail for attempts to create maker order and fill as taker from same account (212ms)
>     ✓ should fail for attempts to order and fill with price changed (195ms)
> 
> 
>   18 passing (6s)

**Comment by cryptomental** [comment]
Hi @pelsasser , I meant copying the test case within the same contract. 

Perhaps your approach is right, to create new contract() wrappers for each group of tests that should be independent from each other.

**Comment by pelsasser** [comment]
@cryptomental - got it.

Good with me closing this issue?

**Comment by cryptomental** [comment]
Yes, that was fine to close this one.
