### ISSUE TITLE
scripts/coverage_run.sh environment variables doesn't seem to be set when using travis

### ISSUE THREAD

**Issue by pelsasser** [MarketProject/MarketProtocol#21]
From what I can tell the CI environment variable in this script is never set correctly so coverage isn't getting reported.  @cryptomental - Can you help me understand where you intended to set this up and I can add it? 

```
+if [ "$CONTINUOUS_INTEGRATION" = true ]; then
 +  cat coverage/lcov.info | node_modules/.bin/coveralls
 +fi
```

**Comment by cryptomental** [comment]
Yes, it just needs to be set up in .env or passed to environment from docker-compose.yml. I will be happy to help.

**Comment by pelsasser** [comment]
thanks @cryptomental will see if I can get it working.

**Comment by pelsasser** [comment]
https://github.com/MarketProject/MarketProtocol/blob/b8b4e0cbfd91a48635ae16d8f15c830190c665da/.travis.yml#L11

`cat coverage/lcov.info | node_modules/.bin/coveralls
`
still not getting called
