### ISSUE TITLE
bring test coverage for MathLib.sol to 100%

### ISSUE THREAD

**Issue by pelsasser** [MarketProject/MarketProtocol#27]

**Comment by pelsasser** [comment]
close #31 killed!

thanks @cryptomental

**Comment by cryptomental** [comment]
You can close this, there is no way that we can programatically trigger the three remaining asserts. They can only by triggered when the solidity compiler is corrupted, so the asserts are there  to stay but will never be covered by tests. The statements, functions and lines coverage is 100%.

**Comment by pelsasser** [comment]
@cryptomental thanks! closing now
