### ISSUE TITLE
Create docker image for MarketProject/ethereum-bridge for docker-compose.yml

### ISSUE THREAD

**Issue by pelsasser** [MarketProject/MarketProtocol#33]
Both of the following should be updated to the forked ethereum-bridge in MarketProject

https://github.com/MarketProject/MarketProtocol/blob/9dc650ed229f19e0df9bda2c06919d127ca18e32/docker-compose.yml#L43

https://github.com/MarketProject/MarketProtocol/blob/9dc650ed229f19e0df9bda2c06919d127ca18e32/docker-compose.yml#L19

**Comment by cryptomental** [comment]
I  will pick it up tomorrow.

**Comment by cryptomental** [comment]
Actually I cannot do it. It has to be someone, likely @pelsasser , who created marketprotocol user in docker hub. The steps are as usual: docker login, docker build, docker tag, docker push, then change Dockerfile, test locally, open a pull request.

**Comment by pelsasser** [comment]
@cryptomental sounds good, will try and get to this today.

**Comment by pelsasser** [comment]
@cryptomental - thanks for the help on this - all set.
