### ISSUE TITLE
set up docker environment

### ISSUE THREAD

**Issue by pelsasser** [MarketProject/MarketProtocol#7]

**Comment by DeathCamel57** [comment]
I'll work on this

**Comment by pelsasser** [comment]
@DeathCamel57 - thanks! @cryptomental may have already started the process if you take a look at the thread for #4

**Comment by DeathCamel57** [comment]
@pelsasser, I don't see any forks that he is working on on his profile page. Any input @cryptomental?

**Comment by cryptomental** [comment]
Hi, my last two days were busy, I think 'hectic' is a correct word. I can have a look at this tomorrow, but feel free to start today if you have time. The difficult part is to synchronize docker-compose to start truffle in dev mode, wait until it is fully initialized then eth-bridge, then migration and tests can start. You can as well start with truffle dev and eth-bridge, and run tests manually. eth-bridge container can base on node:6.9.1 image, and MarketProtocol on the latest one. Cheers.
